Charlies branch
FRC-Team-1710/SubTeamCalculator pull request #4
Opened 2020-11-11 02:03 UTC by TheChar

2020-11-11 02:05 UTC, Andrew-K961 reviewed
Please review my pull request so that you can implement your calculation with the user inputs.

2020-11-11 03:20 UTC, Team1710CTO approved these changes, later dismissed
Great use of parameters! Good communication on the datatypes!

2020-11-11 17:02 UTC, cyrusduong requested changes

2020-11-11 17:02 UTC, cyrusduong commented on MyClass.java
> +        array[3] + " marketers, " + array[4] + " outreachers, " + array[5] + " initiaters,\n" + array[6] + " photographers, " + array[7] + " graphical creators, and " + array[8] + " financers.");
Interesting. This certainly works but is a little hard-ish to read. Since you are using `\n` throughout may I suggest we use multiple `println()` calls instead since it would clean this up? It will be easier to make modifications or additions to this list this way as well.

e.g. -

```
System.out.println(initialLeaderString + " and " + finalLeaderString);
System.out.println("There will be...");
System.out.println(array[0] + " programmers");
System.out.println(array[1] + " builders");
... (etc)
```

Extra challenge: Any way you can print this using a loop? What if we store the labels and values together, then put them in a list? 

> Hint: [Creating a new/helper class](https://www.w3schools.com/java/java_classes.asp) that can hold both the label of the team & the number of members. [Putting those in a list](https://www.w3schools.com/java/java_arraylist.asp). Then accessing the variables of each of those `MySubTeam` objects when you are looping over them to print.

<details>
<summary>SUPER Hint</summary>

``` 
// At top of file with other imports
import java.util.ArrayList;

// Creating a list of `MySubTeam` objects.
ArrayList<MySubTeam> subteams = new ArrayList<MySubTeam>();

// Creating a MySubTeam class to hold the label and number of members for a subteam.
public class MySubTeam {
    private Integer numberOfMembmers;
    private String subTeamName;

    // We need a [Constructor](https://www.w3schools.com/java/java_constructors.asp).

    // We need some [Getters/Setters](https://www.w3schools.com/java/java_encapsulation.asp).
    
    // Any other [methods](https://www.w3schools.com/java/java_class_methods.asp), you might need?

    // Print method - Prints the subteam name and number of members.
    public void printMembers() {
        System.out.println(programmersTeam.subTeamName + " team has " + programmersTeam.numberOfMembers + " memebers.");
    }
}

/**
 * Example usage
 **/
// Creating values "programmers" `MySubClass` object. If you do it this way you'll need to create a constructor to set the values 
programmersTeam = new MySubClass('programming', 5);

// Printing out the number of members
programmersTeam.printMembers();
```

</details>

2020-11-11 17:02 UTC, cyrusduong commented on MyClass.java
> +        array[3] + " marketers, " + array[4] + " outreachers, " + array[5] + " initiaters,\n" + array[6] + " photographers, " + array[7] + " graphical creators, and " + array[8] + " financers.");
Also, I didn't throw this into a compiler. The `SUPER Hint` may have some problems/errors. Might need fixing up.

2020-11-11 20:29 UTC, cyrusduong approved these changes

2020-11-12 04:11 UTC, GavenB141 approved these changes

2020-11-12 14:43 UTC, Team1710CTO approved these changes

2020-11-12 16:55 UTC, merged